apiVersion: v1
baseDomain: ape.dwnstrm
metadata:
  name: sno
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.122.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64 
  hyperthreading: Enabled
  name: master
  replicas: 1
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNGM2MjkzMmU4M2M0NDI4NWEzNzkzMjFjOWZkYWQ1NTM6Q0ZWMlFUT0ZYSTNDMTNVTUE2Q0g5MjVCS0lNRlFGNDNJTFJDTExRRTRXUlRaRFVCSlRRMU43QUFLVFAwODJKUA==","email":"darryl.beetle@roguethink.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNGM2MjkzMmU4M2M0NDI4NWEzNzkzMjFjOWZkYWQ1NTM6Q0ZWMlFUT0ZYSTNDMTNVTUE2Q0g5MjVCS0lNRlFGNDNJTFJDTExRRTRXUlRaRFVCSlRRMU43QUFLVFAwODJKUA==","email":"darryl.beetle@roguethink.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWVlMWU5NjhhLTY0YjItNDI5YS04ZjQzLTAxZGViMGVhNzBhNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTFNVFl4WkRRNVlXWXdNR0kwWlRNMllUUTNNekF4T0RkaVlXVTRaakl6WlNKOS5xZEhqZ1c1UTh4V2ozVDkyQUtGNlhGQTlWQi12VDZSNjFiQ3RJX0hWMm5KUzRRNUNUcm5raEhkaGVoV0VaV3RpVmRlQzczckUzT2FERTlVdUdGMS05YmxjVHgwRF83bDctX2t1MmVESXlocVk5ajdYWU1QNVFLZzM1Y19GMVhKcW1KQVFNVG5tcElyUlBZaTZLWUlMeWdqNkpFOEZ1aDV3VmJ6Z3BjSnpNangzMV85ODkzaDhUR19kaTNVS1c0V2VMZmQ3Z2l6c0xpUWhwWmozSm1zaDQ1QnIzTFRoUW5na0hTQVlwb1VpZWFQSDdVQXVnZ21hU0VXOW5DQ29iYlZLMDNvcmQ4dVVTZ01vTGx2anJKcXNvR3FyRkw1VUpqMGd0Nk1Db0o3QVFfT3F2UmhzbnFQTWo0aHQ4X3A0c3ZoMWxoXzlIRElpLV9RNGNVeVVRWlBfTUJodXVrdklGNXFFQkIwN1BPc0xVcmY0dEhjYzEyeFo4UkFSbHBpaDdkMndmbFRacHI0MmFteTNFM3BKbTNRZTZfaUdxeTZXOUt4R3lMS1pqZ2JCRm9aQ1h3Y1JzUXBVeGFyMzh3c2laYkU1dHFsTHFkSGlrQ0czSkpTdjB3Z3loWVE1WmQwQzRTel9icjZCallaYnVFSjZrc0dVZ1dpVUdrU0IyTThoSlc3ajFwN1BYMlhDMWllN09HQ2ZJdG1QVWRUWlhCRE1Kd204aGxmSDJjVU5fSTdVRXBJWHNYWE9yOTVTeHJkOG9MeW9jakdMX1ZfUTEyRXpVNjYyZWhYajdzZkpFSzI1cWlOX21aYmdwTXgzVWJNaVpjM1FmMzdCZEVlY1hSS01ZSDluMjVTUXk3Vl83b1htVm9VTWRQQkFyNGtuZFF4LXNua1VGamRXcFdPTy1rNA==","email":"darryl.beetle@roguethink.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWVlMWU5NjhhLTY0YjItNDI5YS04ZjQzLTAxZGViMGVhNzBhNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTFNVFl4WkRRNVlXWXdNR0kwWlRNMllUUTNNekF4T0RkaVlXVTRaakl6WlNKOS5xZEhqZ1c1UTh4V2ozVDkyQUtGNlhGQTlWQi12VDZSNjFiQ3RJX0hWMm5KUzRRNUNUcm5raEhkaGVoV0VaV3RpVmRlQzczckUzT2FERTlVdUdGMS05YmxjVHgwRF83bDctX2t1MmVESXlocVk5ajdYWU1QNVFLZzM1Y19GMVhKcW1KQVFNVG5tcElyUlBZaTZLWUlMeWdqNkpFOEZ1aDV3VmJ6Z3BjSnpNangzMV85ODkzaDhUR19kaTNVS1c0V2VMZmQ3Z2l6c0xpUWhwWmozSm1zaDQ1QnIzTFRoUW5na0hTQVlwb1VpZWFQSDdVQXVnZ21hU0VXOW5DQ29iYlZLMDNvcmQ4dVVTZ01vTGx2anJKcXNvR3FyRkw1VUpqMGd0Nk1Db0o3QVFfT3F2UmhzbnFQTWo0aHQ4X3A0c3ZoMWxoXzlIRElpLV9RNGNVeVVRWlBfTUJodXVrdklGNXFFQkIwN1BPc0xVcmY0dEhjYzEyeFo4UkFSbHBpaDdkMndmbFRacHI0MmFteTNFM3BKbTNRZTZfaUdxeTZXOUt4R3lMS1pqZ2JCRm9aQ1h3Y1JzUXBVeGFyMzh3c2laYkU1dHFsTHFkSGlrQ0czSkpTdjB3Z3loWVE1WmQwQzRTel9icjZCallaYnVFSjZrc0dVZ1dpVUdrU0IyTThoSlc3ajFwN1BYMlhDMWllN09HQ2ZJdG1QVWRUWlhCRE1Kd204aGxmSDJjVU5fSTdVRXBJWHNYWE9yOTVTeHJkOG9MeW9jakdMX1ZfUTEyRXpVNjYyZWhYajdzZkpFSzI1cWlOX21aYmdwTXgzVWJNaVpjM1FmMzdCZEVlY1hSS01ZSDluMjVTUXk3Vl83b1htVm9VTWRQQkFyNGtuZFF4LXNua1VGamRXcFdPTy1rNA==","email":"darryl.beetle@roguethink.com"},"mirror-reg.ape.dwnstrm:8443":{"auth":"YWRtaW46UkVHUGFzc3dvcmQx","email":"admin"}}}'
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXtiymbnftzKRgXXuIOSBdrCLVfxyTzhjhsk92uBRIvjhKHqyfHA3m9HKyFagU9Lym0JhMDRaVonIKV6DaXffC6Z51XgSOv1jAVypxDV5+FOb0jtuMMR3DMWkVx24NNgT0pSAS4INPgKmrWIkk9sisN8EeY0VeHqc+kEQybwz3hwEzuKlTgGD433lUQt8OZFQIiR0nMxiQwEDrXm8QCykfBwWQUno8MgWCMnZ4Kt8z4ZokVkJKovaTGLZSOX86h7ZTpQyracgk+9qmh9bpvty2UTwakYupjB/9vAZ1oD/4rBWetr80dllECJRU+SEHfywsl8wF8zF/B4+iCSRZKPjd root@mgnt"
imageDigestSources:
- mirrors:
  - mirror-reg.ape.dwnstrm:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - mirror-reg.ape.dwnstrm:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIESjCCArKgAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MRQwEgYDVQQKDAtBUEUu
  RFdOU1RSTTEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI0MDkw
  OTA5NTY0NloXDTQ0MDkwOTA5NTY0NlowNjEUMBIGA1UECgwLQVBFLkRXTlNUUk0x
  HjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCAaIwDQYJKoZIhvcNAQEB
  BQADggGPADCCAYoCggGBALJ3lJl6ZPJH5jRlSMU7b9F6zUko7/uo1oa6z0jGdmX3
  qh5r0aT1Sx74u2Oq8/r97AMNv+CImVXHGbn6HIRnR3C+lfsPhZkkpPdhZ5UGBa41
  41Y/hB6OnN2Hoxa/hkK55zbrNJlLlpiFP24ZL8ix1zeRv7GTjBDOVDsCg0R3WFDz
  BpKUKgcu4PkjwZgAZ5JXMD2LGFUT1lQZ5jMFXQGaddxTJeeLjafuU95iiRJZMciO
  Q++eKXc1EvXNJu3PqXUXyDyPnRbEszgm/vOURDsFCDwzXQaAQeSfO0P/h26lEZh4
  bdZ6n3yyCHOCybmOCwKnJ6rKmxnjTEYe5IwK8R0Gp1bBW/NoClp+nwfFLdUJbOT2
  JFPGIjtWkvB2iLqySQ5LMUOF/66KwDC98ro7aqN/uGtBA0QanMRR08zHBkRDr8qr
  vgUNiu/Ymqhx3ju6Cx733zIYI0W+tSbqeWIH8wQmdIryS91I2xTWD2kF/klozxYw
  kbHWWu5l9nTC3S+F/96QCwIDAQABo2MwYTAdBgNVHQ4EFgQUm3hRK1EitCgLgI9H
  gzTwvjhRFYQwHwYDVR0jBBgwFoAUm3hRK1EitCgLgI9HgzTwvjhRFYQwDwYDVR0T
  AQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYwDQYJKoZIhvcNAQELBQADggGBADhs
  QGQZb7qGWv4JIIWqnFdrXHfepD7EIqTw/uDpY30qyn+eAkbX/Fm6Z03NBtge+bYa
  hX1AjcwmQJi9YvgEYt5Y83Q3s0rreDCxNo4KFjP1wBBLdoXk8dXKnKUquoBzjwkl
  imEXX1PphJtvrIParGSntRFrvlx4BnRitxMXPHTQy0MAEK5S8aJmCR6C7sJZ1Gv8
  SBKukj0dHNDDpLPX1vKUJAH9Xc+HM4peM5KpZp7SSG1SNpd0idhs+paDh/IHkANv
  7tw48lmnJ2IjH5SOJbfceRyV2lqlyv4xCIocm8io6ZiHA1RKI0zgxaVXhiPjJsXe
  GDTmObcbg3MYR/EDmsQojW0n2HqnPMy+8DrGY/3zgFCUanXQznFtblKPjC2MmfF6
  S1fpe26bTrlz9UQ/sEHYoICSNvBKSiPtV+4D4EhxsP82mTRqXXZn1lO+jo8h/hDr
  2LdzFzQwBsfPHCR2fKO1kGkIa38f4jxhCZglnJsE4Eqqdjqq/v7Qth8nJLYvLA==
  -----END CERTIFICATE-----
additionalTrustBundlePolicy: Always
